services:
  checklist-app:
    container_name: checklist-app
    build: .
    ports: ["8000:8000"]
    networks: [infraestructura_app-network]
    environment:
      - GOOGLE_SHEETS_CREDENTIALS_JSON=/app/credentials.json
      - SHEETS_SPREADSHEET_ID=1I44YXC1eksW3k0xbN4wfsusmaT0oCISwQYyeuUFdrQ4
    volumes:
      - ./credentials.json:/app/credentials.json:ro
      - ./data:/app/data:ro
      - ./uploads:/app/uploads
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.checklist.rule=Host(`checklist.sintaq.net`)"
      - "traefik.http.routers.checklist.entrypoints=websecure"
      - "traefik.http.routers.checklist.tls=true"
      - "traefik.http.routers.checklist.tls.certresolver=cloudflare"
      - "traefik.http.services.checklist.loadbalancer.server.port=8000"
      - "traefik.http.routers.checklist.middlewares=authentik@file"
networks:
  infraestructura_app-network:
    external: true